version: '3.8'
services:
  spring-app:
    container_name: spring-app 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  mysql-compose:
    image: mysql
    environment:
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: 
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
